apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veiculos-service
  template:
    metadata:
      labels:
        app: veiculos-service
    spec:
      containers:
        - name: veiculos
          image: eduardomarcello/veiculos:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: veiculos-service
spec:
  selector:
    app: veiculos-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080